[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dot-suite"
version = "1.0.0"
description = "A meta-package to install the complete dot ecosystem."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Alex Towell", email = "lex@metafunctor.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dotget",
    "dotstar",
    "dotmod",
    "dotbatch",
    "dotpipe",
    "dotquery",
    "dotrelate",
    "dotpath",
    "dotselect",
    "dotexists",
    "dotany",
    "dotall"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
    "mkdocs"
]

[project.urls]
Homepage = "https://github.com/queelius/dot-suite"
